sonar.projectKey=kdutt53-git_8.2CDevSecOps
sonar.organization=kdutt53-git
sonar.host.url=https://sonarcloud.io
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/test/**,**/coverage/**
sonar.sourceEncoding=UTF-8